#!/usr/bin/env python3
#
# vim: ft=python
#
# Convert time string to time stamp

import datetime
import sys

def _to_time(ts):
  try:
    return datetime.datetime.strptime(ts, '%Y-%m-%d %H:%M:%S')
  except:
    return datetime.datetime.strptime(ts, '%Y-%m-%d')

ts = sys.argv[1]
print(int(_to_time(ts).timestamp()))
