#!/usr/bin/env python3
#
# vim: ft=python
#
# Convert time stamp to time string

import datetime
import sys

def _to_time(millis):
  try:
    return datetime.datetime.fromtimestamp(millis)
  except: 
    return datetime.datetime.fromtimestamp(millis / 1000)
  

stamp = int(sys.argv[1])
tm = _to_time(stamp)
print(tm.strftime('%Y-%m-%d %H:%M:%S'))
